swagger: '2.0'
info:
  version: 0.0.1
  title: Events Management API
consumes:
  - multipart/form-data
produces:
  - application/json
schemes:
  - http
  - https
definitions:
  ErrorDetails:
      title: Error details
      type: object
      properties:
        message:
          type: string
          description: error messages
        errors:
          type: array
          items:
            description: error detail
            type: string
paths:
  /api/events:
    get:
      summary: Return list events.
      tags:
       - Event
      description: returns list of information about "event".
      parameters:
        - name: result_limit
          in: query
          description:  Limit count of response record of searching. if not setted,response record limit is 10. minimun value =1,maximun value =100
          required: false
          type: integer
        - name: page
          in: query
          description:  |
           specify the number of page.
           if not seted,the number of page is 1.
          required: false
          type: integer
      responses:
        '200':
          description: Successful response
          schema:
            title: Successful response
            type: object
            properties:
              result_count:
               type: integer
               description:
                Count of result in this response
              event_list:
                type: array
                description: events sorted by DESC
                items:
                    type: object
                    properties:
                      title:
                        type: string
                        description: title of event(except for "#")
                        example: abc
                      start_datetime:
                        type: string
                        description: start time event
                        example: "2006-10-25 00:00:00+00"
                      end_datetime:
                        type: string
                        description: end time event
                        example: "2006-10-29 00:00:00+00"
                      location:
                        type: string
                        description: Event location
                        example: "10 Bạch Đằng, Đà Nẵng"
                      time_notication:
                        type: string
                        description: Time notication
                        example: "2006-10-26 00:00:00+00"
                      owner:
                        type: integer
                        description: User create event
                        example: 1
                      event_content:
                        type: string
                        description: Event Content
                        example: "meeting team"
                      file_attack:
                        type: string
                        description: File attack
                        example: "abc.pdf"
                      guest_can_invite:
                        type: boolean
                        description: Guest can invite
                        example: true
                      view_all_guest:
                        type: boolean
                        description: View all guest
                        example: false
                      item_preparing:
                        type: string
                        description: Item preparing
                        example: "money"
                      status:
                        type: integer
                        description: status event
                        example: 1
                      time_create:
                        type: string
                        description: Time create
                        example: "2006-10-29 00:00:00+00"
                      last_edit:
                        type: string
                        description: Time create
                        example: "00:00:00+00"
                      user_edit:
                        type: integer
                        description: user edit event
                        example: 1
        '400':
          description: Bad request error response
          schema:
            $ref: '#/definitions/ErrorDetails'
        '500':
          description: Internal server error response
          schema:
            $ref: '#/definitions/ErrorDetails'
  /api/event/{id_event}/:
    put:
      summary: update event detail information
      tags:
        - Event
      description: >
        "First": send to server event id and event detail information to be updated
        "Second": update information of event.
        "Finally":return 200      consumes:
        - application/json
      parameters:
        - name: id_event
          in: path
          description: id of event
          required: true
          type: string
        - name: event
          in: body
          description: event to add to the Entity
          required: true
          schema:
            title: event details
            type: object
            properties:
              title:
                type: string
                description: For table "tbl_events" required false
                example: abc
              start_datetime:
                type: string
                description: start time event
                example: "2006-10-25 00:00:00+00"
              end_datetime:
                type: string
                description: end time event
                example: "2006-10-29 00:00:00+00"
              location:
                type: string
                description: Event location
                example: "10 Bạch Đằng, Đà Nẵng"
              time_notication:
                type: string
                description: Time notication
                example: "2006-10-26 00:00:00+00"
              owner:
                type: integer
                description: User create event
                example: 1
              event_content:
                type: string
                description: Event Content
                example: "meeting team"
              file_attack:
                type: string
                description: File attack
                example: "abc.pdf"
              guest_can_invite:
                type: boolean
                description: Guest can invite
                example: true
              view_all_guest:
                type: boolean
                description: View all guest
                example: false
              item_preparing:
                type: string
                description: Item preparing
                example: "money"
              status:
                type: integer
                description: status event
                example: 1
              time_create:
                type: string
                description: Time create
                example: "2006-10-29 00:00:00+00"
              last_edit:
                type: string
                description: Time create
                example: "00:00:00+00"
              user_edit:
                type: integer
                description: user edit event
                example: 1
      responses:
        '200':
          description: Successful response
        '400':
          description: Bad request error response
          schema:
            $ref: '#/definitions/ErrorDetails'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorDetails'
        '403':
          description: Forbidden
          schema:
            $ref: '#/definitions/ErrorDetails'
        '500':
          description: Internal server error response
          schema:
            $ref: '#/definitions/ErrorDetails'
