# Generated by Django 2.1.5 on 2019-01-18 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField(null=True)),
                ('is_daily', models.BooleanField(default=False)),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.TextField(null=True)),
                ('is_notification', models.BooleanField(default=False)),
                ('time_notification', models.CharField(max_length=20, null=True)),
                ('event_content', models.TextField(null=True)),
                ('file_attack', models.TextField(null=True)),
                ('guest_can_invite', models.BooleanField(default=True)),
                ('view_all_guest', models.BooleanField(default=True)),
                ('item_preparing', models.TextField(null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField()),
                ('last_edit', models.DateTimeField()),
                ('status', models.IntegerField(null=True)),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, related_name='fk_owner_event', to=settings.AUTH_USER_MODEL)),
                ('user_edit', models.ForeignKey(db_column='user_edit', on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_edit_event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_events',
            },
        ),
        migrations.CreateModel(
            name='EventHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(null=True)),
                ('end_date', models.DateField()),
                ('end_time', models.TimeField(null=True)),
                ('is_daily', models.BooleanField(default=False)),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.TextField(null=True)),
                ('is_notification', models.BooleanField(default=False)),
                ('time_notification', models.CharField(max_length=20, null=True)),
                ('event_content', models.TextField(null=True)),
                ('file_attack', models.TextField(null=True)),
                ('guest_can_invite', models.BooleanField(default=True)),
                ('view_all_guest', models.BooleanField(default=True)),
                ('item_preparing', models.TextField(null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('time_create', models.DateTimeField()),
                ('last_edit', models.DateTimeField()),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, related_name='fk_owner_event_history', to=settings.AUTH_USER_MODEL)),
                ('user_edit', models.ForeignKey(db_column='user_edit', on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_edit_event_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_events_history',
            },
        ),
        migrations.CreateModel(
            name='EventMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_going', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('invite_id', models.IntegerField(null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_event_members',
            },
        ),
    ]
